### ISSUE TITLE
Problems with TCP connections idle longer than 55-ish seconds

### ISSUE THREAD

**Issue by mtackes** [sparkfun/SFE_CC3000_Library#15]
I've been testing a project that uses long-running TCP connections and started noticing problems once the connection was held open but idle for longer than around 55 seconds. The CC3000 appears to stop receiving any data without ever hitting the 'disconnect' code and the server is not (usually) informed that the connection was closed.

I've run several tests on my local wifi network (haven't had time to test with another access point, but that's on my list) with a few different servers on a few different machines, and the result always appears to be the same. The time does seem to vary by the server; the Node.js server I'm working on hits the issue at just after 51 seconds, while a simple iOS TCP tool I downloaded seems to work until around the 57 second mark.

The BoardTest sketch indicates I'm running firmware version 1.24. If I understand correctly, this is package version [1.11.1](http://processors.wiki.ti.com/index.php/CC3000_Release_Notes#Version_1.11.1:). This issue might be fixed in package version [1.13](http://processors.wiki.ti.com/index.php/CC3000_Release_Notes#Version_1.13:) (firmware version 1.28, "Fixing the automatic ARP updates in the network stack which would make the long running TCP operations to hang."). Even that update fixes the issue, I'm not familiar enough with Arduinos or C/C++ to know how to install it.

While I can work around the issue by checking forcing timeouts and reconnects before the problem occurs, I'd still love to know what's going on here, and was curious if anyone had any answers.

**Comment by ShawnHymel** [comment]
If you are interested in trying to update the firmware, I recommend trying that by seeing these tutorials: [here](https://learn.adafruit.com/adafruit-cc3000-wifi/firmware-upgrades) or [here](http://processors.wiki.ti.com/index.php/CC3000_Patch_Programmer).

**Comment by mtackes** [comment]
Did a little more digging, and I found [this closed issue](/adafruit/Adafruit_CC3000_Library/issues/147) from the Adafruit version of the CC3000 lib. Looks like ~60 seconds is the default, but it can be configured, so I'm marking this as closed.
